version: '3'

services:
  db:
    container_name: db
    image: mongo:4.4.19-rc2
    command: "--auth"
    volumes:
      - type: volume
        source: db-volume
        target: /data/db
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - net

  express:
    container_name: express
    build:
      context: ./
      dockerfile: express.Dockerfile
    volumes:
      - type: volume
        source: express-volume
        target: /app
    ports:
      - "3000:3000"
    working_dir: '/app'
    entrypoint: sh /tmp/express.entry.sh;
    networks:
      - net

volumes:
  db-volume:
    name: db-volume
    driver: local
    driver_opts:
      device: ${PWD}/db
      type: none
      o: bind

  express-volume:
    name: express-volume
    driver: local
    driver_opts:
      device: ${PWD}/express
      type: none
      o: bind

networks:
  net:
    name: internal
    driver: bridge
