version: '3'

services:
  db:
    container_name: db
    image: mongo:4.4.19-rc2
    command: "--auth"
    volumes:
      - type: volume
        source: db-volume
        target: /data/db
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - net

  backend:
    container_name: backend
    build:
      dockerfile: backend.Dockerfile
      context: ./
    volumes:
      - type: volume
        source: backend-volume
        target: /app
    ports:
      - "3000:3000"
    entrypoint: sh /tmp/backend.entry.sh
    networks:
      - net

  frontend:
    container_name: frontend
    build:
      dockerfile: frontend.Dockerfile
      context: ./
    volumes:
      - type: volume
        source: frontend-volume
        target: /app
    ports:
      - "8080:8080"
    entrypoint: sh /tmp/frontend.entry.sh
    networks:
      - net

volumes:
  db-volume:
    name: db-volume
    driver: local
    driver_opts:
      device: ${PWD}/db
      type: none
      o: bind

  backend-volume:
    name: backend-volume
    driver: local
    driver_opts:
      device: ${PWD}/backend
      type: none
      o: bind

  frontend-volume:
    name: frontend-volume
    driver: local
    driver_opts:
      device: ${PWD}/frontend
      type: none
      o: bind

networks:
  net:
    name: internal
    driver: bridge
