version: '3'

services:
  db:
    container_name: db
    image: mongo:4.4.19-rc2
    command: "--auth"
    volumes:
      - type: volume
        source: db-volume
        target: /data/db
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - net

  backend:
    container_name: backend
    image: node:19-alpine3.16
    volumes:
      - type: volume
        source: backend-volume
        target: /app
    ports:
      - "3000:3000"
    working_dir: '/app'
    entrypoint: npm run start:dev
    networks:
      - net

volumes:
  db-volume:
    name: db-volume
    driver: local
    driver_opts:
      device: ${PWD}/db
      type: none
      o: bind

  backend-volume:
    name: backend-volume
    driver: local
    driver_opts:
      device: ${PWD}/backend
      type: none
      o: bind

networks:
  net:
    name: internal
    driver: bridge
